// SPDX-License-Identifier: MIT
pragma solidity ^0.8.27;

import { Test, console } from "forge-std/Test.sol";
import { TeeResultVerifier } from "../contracts/libraries/TeeResultVerifier.sol";

/// @notice Emits a signed TEE result vector for the frontend verifier to check itself against.
///
/// @dev `frontend/lib/verify.ts` re-derives the TEE signature chain in the browser, deliberately
///      duplicating `TeeResultVerifier.sol` rather than calling it — two independent
///      implementations agreeing is evidence, one calling itself is not.
///
///      But "independent" only helps if they are actually compared. This test signs a result with a
///      known key and prints every intermediate hash, so the TypeScript tests can assert they
///      reproduce each step and recover the same signer. Without it, the duplication is just
///      duplication.
///
///      Regenerate with:
///        forge test --match-test test_emitSigVector -vv
contract GenerateSigVectorsTest is Test {
    /// @dev Wrapper so the library's calldata parameters can be supplied from a memory value.
    function resultHash(
        bytes calldata _data,
        bytes32 _actionId,
        string calldata _tag,
        uint8 _status
    ) external pure returns (bytes32) {
        return TeeResultVerifier.resultHash(_data, _actionId, _tag, _status);
    }

    function payloadHash(bytes32 _resultHash) external view returns (bytes32) {
        return TeeResultVerifier.payloadHash(_resultHash);
    }

    function test_emitSigVector() public view {
        uint256 pk = 0xA11CE;
        address signer = vm.addr(pk);

        // A realistic allocation result: the exact tuple Fidensur.finalizeRound decodes.
        bytes memory data = abi.encode(
            address(0x00000000000000000000000000000000000000C0), // contractAddr
            uint256(7),                                          // roundId
            keccak256("policy-commitment"),                      // policyCommitment
            keccak256("merkle-root"),                            // merkleRoot
            uint256(123456789),                                  // totalAllocated
            uint32(42),                                          // recipientCount
            bytes32("0.1.0")                                     // engineVersion
        );

        bytes32 actionId = keccak256("instruction-id");
        string memory tag = "submit";
        uint8 status = 1;

        bytes32 rh = this.resultHash(data, actionId, tag, status);
        bytes32 ph = this.payloadHash(rh);
        bytes32 digest = keccak256(abi.encodePacked("\x19Ethereum Signed Message:\n32", ph));

        (uint8 v, bytes32 r, bytes32 s) = vm.sign(pk, digest);
        bytes memory signature = abi.encodePacked(r, s, v);

        console.log("{");
        console.log('  "note": "Generated by test/GenerateSigVectors.t.sol. Do not edit by hand.",');
        console.log(string.concat('  "chainId": ', vm.toString(block.chainid), ","));
        console.log(string.concat('  "signer": "', vm.toString(signer), '",'));
        console.log(string.concat('  "data": "', vm.toString(data), '",'));
        console.log(string.concat('  "actionId": "', vm.toString(actionId), '",'));
        console.log(string.concat('  "submissionTag": "', tag, '",'));
        console.log(string.concat('  "status": ', vm.toString(uint256(status)), ","));
        console.log(string.concat('  "dataHash": "', vm.toString(keccak256(data)), '",'));
        console.log(string.concat('  "resultHash": "', vm.toString(rh), '",'));
        console.log(string.concat('  "payloadHash": "', vm.toString(ph), '",'));
        console.log(string.concat('  "eip191Digest": "', vm.toString(digest), '",'));
        console.log(string.concat('  "signature": "', vm.toString(signature), '"'));
        console.log("}");
    }
}
