// SPDX-License-Identifier: MIT
pragma solidity ^0.8.27;

import { Test, console } from "forge-std/Test.sol";
import { AllocationMerkle } from "../contracts/libraries/AllocationMerkle.sol";
import { MerkleBuilder } from "./helpers/MerkleBuilder.sol";

/// @notice Emits cross-implementation test vectors.
///
/// @dev The Go allocation engine builds Merkle trees and the Solidity library verifies them. If the
///      two ever disagree, every claim in a round fails — and the failure looks like a bad proof,
///      not like a version skew, which is a miserable thing to debug in production.
///
///      This test prints leaf hashes and roots computed by the Solidity side. The values are
///      committed to extension/internal/engine/testdata/merkle_vectors.json and asserted by
///      TestMerkleVectorsMatchSolidity in Go, so `go test` checks the Go implementation against
///      ground truth produced by the code that will actually verify the proofs on-chain.
///
///      Regenerate with:
///        forge test --match-test test_emitVectors -vv
contract GenerateVectorsTest is Test {
    function test_emitVectors() public pure {
        console.log("{");
        console.log('  "note": "Generated by test/GenerateVectors.t.sol. Do not edit by hand.",');

        // --- leaf vectors ---
        console.log('  "leaves": [');
        _leafVector(1, 0, 0x1000000000000000000000000000000000000001, 1_000_000_000_000_000_000, false);
        _leafVector(1, 1, 0x1000000000000000000000000000000000000002, 2_500_000_000_000_000_000, false);
        _leafVector(42, 7, address(uint160(0xaB)), 1, false);
        _leafVector(0, 0, address(type(uint160).max), 0, true);
        console.log("  ],");

        // --- root vectors for sizes 1..8, plus 17 to exercise deep odd promotion ---
        console.log('  "roots": [');
        _rootVector(1, 1, false);
        _rootVector(1, 2, false);
        _rootVector(1, 3, false);
        _rootVector(1, 4, false);
        _rootVector(1, 5, false);
        _rootVector(1, 6, false);
        _rootVector(1, 7, false);
        _rootVector(1, 8, false);
        _rootVector(9, 17, true);
        console.log("  ]");
        console.log("}");
    }

    function _leafVector(uint256 roundId, uint256 index, address recipient, uint256 amount, bool last)
        private
        pure
    {
        console.log("    {");
        console.log(string.concat('      "roundId": "', vm.toString(roundId), '",'));
        console.log(string.concat('      "index": ', vm.toString(index), ","));
        console.log(string.concat('      "recipient": "', vm.toString(recipient), '",'));
        console.log(string.concat('      "amount": "', vm.toString(amount), '",'));
        console.log(
            string.concat(
                '      "leaf": "',
                vm.toString(AllocationMerkle.leafHash(roundId, index, recipient, amount)),
                '"'
            )
        );
        console.log(last ? "    }" : "    },");
    }

    /// @dev Deterministic synthetic table: recipient i is address(0x1000 + i), amount (i+1) * 1e18.
    ///      The Go test builds the same table from the same rule and must reach the same root.
    function _rootVector(uint256 roundId, uint256 n, bool last) private pure {
        bytes32[] memory leaves = new bytes32[](n);
        for (uint256 i = 0; i < n; ++i) {
            leaves[i] = AllocationMerkle.leafHash(
                roundId, i, address(uint160(0x1000 + i)), (i + 1) * 1e18
            );
        }

        console.log("    {");
        console.log(string.concat('      "roundId": "', vm.toString(roundId), '",'));
        console.log(string.concat('      "size": ', vm.toString(n), ","));
        console.log(string.concat('      "root": "', vm.toString(MerkleBuilder.root(leaves)), '"'));
        console.log(last ? "    }" : "    },");
    }
}
