/**
 * One confidential round, end to end, against a live deployment.
 *
 * ## What this is for
 *
 * Every other test in this repository proves internal consistency. Forge tests prove the contract
 * agrees with itself, Go tests prove the engine agrees with itself, and the TypeScript tests prove
 * the browser libraries agree with vectors generated by the other two.
 *
 * None of that can prove the one thing that matters most: that the ECIES ciphertext produced by
 * `lib/ecies.ts` in a browser is decryptable by go-ethereum's `ecies` package inside the enclave.
 * A self-test cannot catch this, because two implementations that are identically wrong round-trip
 * against each other perfectly. Only a real enclave can answer it, and only by trying.
 *
 * So this script deliberately imports the *browser* modules — not a reimplementation of them. If
 * the organisation console would fail, this fails, in the same place, for the same reason.
 *
 * ## What it proves when it passes
 *
 *   1. Browser ECIES → enclave decrypt        (steps 4–7: the policy is understood)
 *   2. Enclave ECIES → browser decrypt        (step 12: the disclosure is readable)
 *   3. The full instruction lifecycle          contract → registry → proxy → node → extension →
 *                                              signed result → on-chain verification
 *   4. The Merkle scheme across all four independent implementations, since the proof is built in
 *      Go, checked in TypeScript, and spent against Solidity.
 *
 * ## Cost
 *
 * Real Coston2 testnet funds. Small — the default allocates 0.002 C2FLR across three recipients,
 * and the instruction fee is 1,000,000 wei per instruction (the value the Flare scaffold uses).
 * The deployer is deliberately one of the three recipients, so the claim step can run without
 * funding a second account for gas.
 */

import {
  createPublicClient,
  createWalletClient,
  decodeAbiParameters,
  defineChain,
  formatEther,
  http,
  parseEventLogs,
  type Address,
  type Hex,
} from "viem";
import { privateKeyToAccount } from "viem/accounts";

import {
  FIDENSUR_EVENTS_ABI,
  FIDENSUR_READ_ABI,
  FIDENSUR_WRITE_ABI,
  NATIVE_TOKEN,
  statusName,
} from "../../frontend/lib/contracts.ts";
import { decryptDisclosure, generateDisclosureKeypair } from "../../frontend/lib/ecies.ts";
import { checkDisclosure, type Disclosure } from "../../frontend/lib/merkle.ts";
import { AllocationMode, randomSalt, sealPolicy, type Policy } from "../../frontend/lib/policy.ts";
import { ProxyClient } from "../../frontend/lib/proxy.ts";
import {
  ALLOCATION_RESULT_ABI,
  assessAttestation,
  decodeVersion,
  verifyActionResult,
  type AllocationResult,
} from "../../frontend/lib/verify.ts";

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

const CHAIN_URL = requireEnv("CHAIN_URL");
const CONTRACT = requireEnv("FIDENSUR_CONTRACT") as Address;
const PROXY_URL = requireEnv("EXT_PROXY_URL");
const PRIVATE_KEY = normalizeKey(requireEnv("DEPLOYMENT_PRIVATE_KEY"));

/** Matches `opts.Value` in the scaffold's `SendSayHello`. Unused value is refunded to the caller. */
const INSTRUCTION_FEE = BigInt(process.env.INSTRUCTION_FEE_WEI ?? "1000000");
const CHAIN_ID = Number(process.env.CHAIN_ID ?? "114");
/** One hour is plenty for a scripted run and short enough to sweep the remainder soon after. */
const CLAIM_WINDOW = BigInt(process.env.CLAIM_WINDOW ?? "3600");

/**
 * Two throwaway co-recipients.
 *
 * These are the standard Anvil development keys — published in Foundry's own documentation and
 * therefore known to everyone on earth. That is exactly why they are safe here and must never hold
 * value: they exist only to give the policy more than one entry, so the Merkle tree has real
 * internal nodes rather than collapsing to a single leaf.
 */
const CO_RECIPIENT_KEYS: Hex[] = [
  "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d",
  "0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a",
];

/** Allocations in wei. The deployer's share is first and is the one that gets claimed. */
const SHARES = [1_000_000_000_000_000n, 700_000_000_000_000n, 300_000_000_000_000n];

const coston2 = defineChain({
  id: CHAIN_ID,
  name: "Coston2",
  nativeCurrency: { name: "Coston2 Flare", symbol: "C2FLR", decimals: 18 },
  rpcUrls: { default: { http: [CHAIN_URL] } },
});

// ---------------------------------------------------------------------------
// Output helpers
// ---------------------------------------------------------------------------

let stepNumber = 0;
function step(title: string): void {
  stepNumber += 1;
  console.log(`\n\x1b[1m── ${stepNumber}. ${title}\x1b[0m`);
}
function info(label: string, value: unknown): void {
  console.log(`   ${label.padEnd(22)} ${value}`);
}
function ok(message: string): void {
  console.log(`   \x1b[32mok\x1b[0m    ${message}`);
}
function fail(message: string): never {
  console.error(`\n\x1b[31mFAILED\x1b[0m  ${message}\n`);
  process.exit(1);
}

function requireEnv(name: string): string {
  const value = process.env[name];
  if (!value) {
    console.error(`error: ${name} is not set. Run this through ./scripts/test.sh, which loads .env.`);
    process.exit(1);
  }
  return value;
}

/** Accepts a key with or without `0x`, since .env files in this project store it bare. */
function normalizeKey(key: string): Hex {
  const bare = key.startsWith("0x") ? key.slice(2) : key;
  if (!/^[0-9a-fA-F]{64}$/.test(bare)) {
    fail("DEPLOYMENT_PRIVATE_KEY must be 64 hex characters");
  }
  return `0x${bare}` as Hex;
}

// ---------------------------------------------------------------------------

const account = privateKeyToAccount(PRIVATE_KEY);
const publicClient = createPublicClient({ chain: coston2, transport: http(CHAIN_URL) });
const walletClient = createWalletClient({ account, chain: coston2, transport: http(CHAIN_URL) });
const proxy = new ProxyClient(PROXY_URL);

/** Sends a transaction and waits for it, failing loudly on revert rather than continuing. */
async function send(functionName: string, args: unknown[], value = 0n): Promise<Hex> {
  const { request } = await publicClient.simulateContract({
    address: CONTRACT,
    abi: FIDENSUR_WRITE_ABI,
    functionName,
    args,
    account,
    value,
  } as never);

  const hash = await walletClient.writeContract(request as never);
  const receipt = await publicClient.waitForTransactionReceipt({ hash });
  if (receipt.status !== "success") fail(`${functionName} reverted (tx ${hash})`);
  info(`${functionName} tx`, hash);
  return hash;
}

async function main(): Promise<void> {
  console.log("\n\x1b[1mFidensur — end-to-end confidential round\x1b[0m");
  info("contract", CONTRACT);
  info("chain", `${CHAIN_URL} (id ${CHAIN_ID})`);
  info("proxy", PROXY_URL);
  info("organization", account.address);

  // -------------------------------------------------------------------------
  step("Preflight");
  // Everything checkable without spending anything. A round that dies at step 9 because
  // teeAddress was never set has cost real transactions to discover a fact readable up front.

  const balance = await publicClient.getBalance({ address: account.address });
  info("balance", `${formatEther(balance)} C2FLR`);
  const budget = SHARES.reduce((a, b) => a + b, 0n);
  if (balance < budget * 4n) {
    fail(`balance too low. Need well over ${formatEther(budget)} C2FLR plus gas. Fund ${account.address}`);
  }

  const [teeAddress, extensionId] = await Promise.all([
    publicClient.readContract({ address: CONTRACT, abi: FIDENSUR_READ_ABI, functionName: "teeAddress" }),
    publicClient.readContract({ address: CONTRACT, abi: FIDENSUR_READ_ABI, functionName: "extensionId" }),
  ]);
  info("teeAddress()", teeAddress);
  info("extensionId()", extensionId);
  if (teeAddress === "0x0000000000000000000000000000000000000000") {
    fail("teeAddress is unset — finalizeRound would revert. Run setTeeAddress first.");
  }

  const attestation = await proxy.attestation();
  if (!attestation) fail(`proxy at ${PROXY_URL} reported no machine data — is the TEE node running?`);

  // The chain reports the extension as a number; the proxy reports it as a 32-byte hex string.
  // Comparing the two notations directly is what produced a phantom mismatch in check-tee-status.sh.
  const expectedExtensionIdHex = `0x${(extensionId as bigint).toString(16).padStart(64, "0")}`;
  const verdict = assessAttestation(attestation, expectedExtensionIdHex);
  info("platform", verdict.isRealPlatform ? "real (GCP AMD SEV)" : "TEST_PLATFORM");
  info("code hash", verdict.isSimulatedCodeHash ? "simulated (not measured)" : "measured");
  if (!verdict.matchesRegisteredExtension) {
    // Not fatal on its own, but it is the cause of MachineManager.TooMany() several steps later,
    // and saying so here is far cheaper than diagnosing it there.
    console.log(
      `   \x1b[33mwarn\x1b[0m  proxy serves extension ${attestation.extensionId},\n` +
        `         but the contract addresses ${expectedExtensionIdHex}`,
    );
  }
  if (!verdict.trustworthy) {
    // Expected on Coston2 and not a reason to stop — but it must be said out loud, because a run
    // that prints "PROVEN" against a simulated enclave proves interoperability, not confidentiality.
    console.log("   \x1b[33mnote\x1b[0m  simulated attestation: this run proves correctness, not confidentiality");
  }

  const teePubKey = await proxy.extensionPublicKey();
  info("TEE public key", `${teePubKey.slice(0, 18)}… (${(teePubKey.length - 2) / 2} bytes)`);
  ok("preflight passed");

  // -------------------------------------------------------------------------
  step("Create the round");

  const createHash = await send("createRound", [NATIVE_TOKEN, CLAIM_WINDOW]);
  const createReceipt = await publicClient.getTransactionReceipt({ hash: createHash });
  const created = parseEventLogs({
    abi: FIDENSUR_EVENTS_ABI,
    eventName: "RoundCreated",
    logs: createReceipt.logs,
  });
  if (created.length === 0) fail("no RoundCreated event in the receipt");
  const roundId = created[0]!.args.roundId as bigint;
  info("roundId", roundId);

  // -------------------------------------------------------------------------
  step("Fund it");

  await send("fund", [roundId, budget], budget);
  info("funded", `${formatEther(budget)} C2FLR`);

  // -------------------------------------------------------------------------
  step("Build and seal the policy");
  // This is the confidential half. Everything below happens locally; only the ciphertext leaves.

  const coRecipients = CO_RECIPIENT_KEYS.map((k) => privateKeyToAccount(k).address);
  const recipients: Address[] = [account.address, ...coRecipients];

  const policy: Policy = {
    contractAddr: CONTRACT,
    roundId,
    organization: account.address,
    mode: AllocationMode.Explicit,
    totalBudget: budget,
    minAlloc: 0n,
    maxAlloc: 0n,
    bands: [],
    salt: randomSalt(),
    entries: recipients.map((recipient, i) => ({ recipient, weight: 0n, amount: SHARES[i]! })),
  };

  recipients.forEach((r, i) => info(`recipient ${i}`, `${r}  ${formatEther(SHARES[i]!)} C2FLR`));

  const sealed = await sealPolicy(policy, teePubKey);
  info("ciphertext", `${(sealed.ciphertext.length - 2) / 2} bytes`);
  info("commitment", sealed.commitment);
  ok("policy encrypted with lib/ecies.ts — the browser's code path");

  // -------------------------------------------------------------------------
  step("Commit to it on-chain");

  await send("submitPolicy", [roundId, sealed.commitment]);
  ok("commitment recorded; the plaintext has never left this process");

  // -------------------------------------------------------------------------
  step("Request the computation");

  const computeHash = await send("requestCompute", [roundId, sealed.ciphertext], INSTRUCTION_FEE);
  const computeReceipt = await publicClient.getTransactionReceipt({ hash: computeHash });
  const requested = parseEventLogs({
    abi: FIDENSUR_EVENTS_ABI,
    eventName: "ComputeRequested",
    logs: computeReceipt.logs,
  });
  if (requested.length === 0) fail("no ComputeRequested event in the receipt");
  const computeId = requested[0]!.args.instructionId as Hex;
  info("instructionId", computeId);
  info("routed to", (requested[0]!.args.teeIds as Address[]).join(", "));

  // -------------------------------------------------------------------------
  step("Wait for the enclave");
  // The moment of truth. A status-0 result here with a decrypt error in its log is the ECIES
  // incompatibility this whole script exists to detect.

  console.log("   polling the proxy — the instruction must be picked up by a data provider first");
  const computeResult = await proxy.waitForResult(computeId, { timeoutMs: 240_000, intervalMs: 5_000 });
  info("status", computeResult.status);
  if (computeResult.status !== 1) {
    fail(
      `the enclave rejected the instruction.\n` +
        `        log: ${computeResult.log ?? "(none)"}\n\n` +
        `        If that mentions decryption, the browser's ECIES output is not readable by\n` +
        `        go-ethereum's ecies package — which is exactly what this script is for.`,
    );
  }
  ok("the enclave decrypted the policy and returned a signed result");
  ok("browser ECIES → enclave decrypt: PROVEN");

  // -------------------------------------------------------------------------
  step("Verify the signature — locally, then on-chain");

  const steps = await verifyActionResult(computeResult, teeAddress as Address, CHAIN_ID);
  info("recovered signer", steps.recoveredSigner ?? "(recovery failed)");
  info("expected signer", steps.expectedSigner);
  if (!steps.valid) fail(`local verification failed: ${steps.error ?? "signer mismatch"}`);
  ok("verified in TypeScript");

  const [onChainValid, onChainSigner] = (await publicClient.readContract({
    address: CONTRACT,
    abi: FIDENSUR_READ_ABI,
    functionName: "checkTeeResult",
    args: [
      computeResult.data,
      computeResult.actionId,
      computeResult.submissionTag,
      computeResult.status,
      computeResult.signature,
    ],
  })) as [boolean, Address];
  if (!onChainValid) fail(`the contract rejected the signature (recovered ${onChainSigner})`);
  ok("verified in Solidity — two independent implementations agree");

  // -------------------------------------------------------------------------
  step("Inspect the aggregate");

  // The layout is seven flat parameters, not a tuple — decoding returns a positional array.
  const decoded = decodeAbiParameters(ALLOCATION_RESULT_ABI, computeResult.data);
  const result: AllocationResult = {
    contractAddr: decoded[0],
    roundId: decoded[1],
    policyCommitment: decoded[2],
    merkleRoot: decoded[3],
    totalAllocated: decoded[4],
    recipientCount: decoded[5],
    engineVersion: decoded[6],
  };

  info("merkleRoot", result.merkleRoot);
  info("totalAllocated", `${formatEther(result.totalAllocated)} C2FLR`);
  info("recipientCount", result.recipientCount);
  info("engineVersion", decodeVersion(result.engineVersion));

  // These four are exactly what finalizeRound checks. Verifying them here means a mismatch is
  // reported in plain language rather than as an opaque revert one step later.
  if (result.contractAddr.toLowerCase() !== CONTRACT.toLowerCase()) {
    fail(`result targets contract ${result.contractAddr}, not ${CONTRACT}`);
  }
  if (result.roundId !== roundId) fail(`result is for round ${result.roundId}, not ${roundId}`);
  if (result.policyCommitment.toLowerCase() !== sealed.commitment.toLowerCase()) {
    fail(`result commits to ${result.policyCommitment}, but we submitted ${sealed.commitment}`);
  }
  if (result.totalAllocated !== budget) {
    fail(`enclave allocated ${result.totalAllocated} but the policy totalled ${budget}`);
  }
  if (Number(result.recipientCount) !== recipients.length) {
    fail(`enclave counted ${result.recipientCount} recipients, expected ${recipients.length}`);
  }
  ok("the aggregate matches what the policy specified, and binds to this contract and round");

  // -------------------------------------------------------------------------
  step("Finalize the round");

  await send("finalizeRound", [
    computeResult.data,
    computeResult.actionId,
    computeResult.submissionTag,
    computeResult.status,
    computeResult.signature,
  ]);
  const round = (await publicClient.readContract({
    address: CONTRACT,
    abi: FIDENSUR_READ_ABI,
    functionName: "getRound",
    args: [roundId],
  })) as { status: number; merkleRoot: Hex };
  info("round status", `${round.status} = ${statusName(round.status)}`);
  ok("the root is on-chain; no individual allocation is");

  // -------------------------------------------------------------------------
  step("Request a disclosure (as a recipient)");
  // The organisation and the recipient are the same address here only so the claim can be paid
  // for. The contract stamps msg.sender into the request, so the enclave is answering the
  // recipient, not the organisation.

  const disclosureKey = generateDisclosureKeypair();
  info("disclosure pubkey", `${disclosureKey.compressed.slice(0, 18)}… (33 bytes)`);

  const discloseHash = await send(
    "requestDisclosure",
    [roundId, disclosureKey.compressed],
    INSTRUCTION_FEE,
  );
  const discloseReceipt = await publicClient.getTransactionReceipt({ hash: discloseHash });
  const discloseLogs = parseEventLogs({
    abi: [
      {
        type: "event",
        name: "DisclosureRequested",
        inputs: [
          { name: "roundId", type: "uint256", indexed: true },
          { name: "requester", type: "address", indexed: true },
          { name: "instructionId", type: "bytes32", indexed: true },
        ],
      },
    ] as const,
    logs: discloseReceipt.logs,
  });
  if (discloseLogs.length === 0) fail("no DisclosureRequested event in the receipt");
  const discloseId = discloseLogs[0]!.args.instructionId as Hex;
  info("instructionId", discloseId);

  // -------------------------------------------------------------------------
  step("Decrypt the disclosure");

  const discloseResult = await proxy.waitForResult(discloseId, { timeoutMs: 240_000, intervalMs: 5_000 });
  if (discloseResult.status !== 1) {
    fail(`disclosure failed. log: ${discloseResult.log ?? "(none)"}`);
  }

  const [requester, disclosedRound, ciphertext] = decodeAbiParameters(
    [{ type: "address" }, { type: "uint256" }, { type: "bytes" }],
    discloseResult.data,
  ) as [Address, bigint, Hex];
  info("addressed to", requester);
  if (requester.toLowerCase() !== account.address.toLowerCase()) {
    fail(`disclosure is addressed to ${requester}, not ${account.address}`);
  }
  if (disclosedRound !== roundId) fail(`disclosure is for round ${disclosedRound}, not ${roundId}`);

  const disclosure = await decryptDisclosure<Disclosure>(ciphertext, disclosureKey.privateKey);
  info("index", disclosure.index);
  info("amount", `${formatEther(BigInt(disclosure.amount))} C2FLR`);
  info("proof length", `${disclosure.proof.length} sibling hashes`);
  ok("enclave ECIES → browser decrypt: PROVEN");

  // -------------------------------------------------------------------------
  step("Check the proof before spending it");

  if (disclosure.recipient.toLowerCase() !== account.address.toLowerCase()) {
    fail(`the disclosure names ${disclosure.recipient}, not ${account.address}`);
  }

  const check = checkDisclosure(disclosure, round.merkleRoot);
  info("root matches chain", check.rootMatches);
  info("proof valid", check.proofValid);
  if (!check.ok) {
    fail(
      check.rootMatches
        ? "the proof does not verify against the root — the Merkle implementations disagree"
        : `the enclave reported root ${disclosure.merkleRoot} but the chain holds ${round.merkleRoot}`,
    );
  }
  ok("the proof verifies in TypeScript against the root the contract holds");

  if (BigInt(disclosure.amount) !== SHARES[0]!) {
    fail(`the enclave allocated ${disclosure.amount}, the policy said ${SHARES[0]}`);
  }
  ok("the amount matches the policy exactly");

  // -------------------------------------------------------------------------
  step("Claim");

  const before = await publicClient.getBalance({ address: account.address });
  await send("claim", [
    roundId,
    BigInt(disclosure.index),
    BigInt(disclosure.amount),
    disclosure.proof,
  ]);
  const after = await publicClient.getBalance({ address: account.address });
  info("balance delta", `${formatEther(after - before)} C2FLR (net of gas)`);
  ok("Solidity accepted a proof built in Go and checked in TypeScript");

  // -------------------------------------------------------------------------
  console.log("\n\x1b[1;32m═══ round complete ═══\x1b[0m");
  console.log(`
  Proven end to end:
    • browser ECIES is byte-compatible with go-ethereum's        (step 7)
    • the enclave's ECIES is readable by the browser             (step 12)
    • the TEE signature verifies in TypeScript and in Solidity   (step 8)
    • the Merkle scheme agrees across Go, TypeScript and Solidity (steps 13–14)

  Round ${roundId} is finalized on-chain. It publishes a root, a total and a count —
  and no individual allocation.
`);
}

main().catch((error) => {
  fail(error instanceof Error ? (error.stack ?? error.message) : String(error));
});
