package engine

import (
	"encoding/json"
	"math/big"
	"os"
	"testing"

	"github.com/ethereum/go-ethereum/common"
)

// Cross-implementation tests.
//
// The Go engine builds Merkle trees and the Solidity library verifies the resulting proofs
// on-chain. Nothing forces the two to agree — they are separate implementations in separate
// languages — and if they drift, every claim in a round fails with "bad Merkle proof", which looks
// like a corrupted proof rather than a version skew. That is an expensive thing to debug in
// production and a cheap thing to catch here.
//
// testdata/merkle_vectors.json is generated by test/GenerateVectors.t.sol, i.e. by the same
// Solidity code that will do the verifying. These tests assert the Go side reproduces it exactly.

type merkleVectors struct {
	Leaves []struct {
		RoundID   string `json:"roundId"`
		Index     uint64 `json:"index"`
		Recipient string `json:"recipient"`
		Amount    string `json:"amount"`
		Leaf      string `json:"leaf"`
	} `json:"leaves"`
	Roots []struct {
		RoundID string `json:"roundId"`
		Size    int    `json:"size"`
		Root    string `json:"root"`
	} `json:"roots"`
}

func loadVectors(t *testing.T) merkleVectors {
	t.Helper()

	raw, err := os.ReadFile("testdata/merkle_vectors.json")
	if err != nil {
		t.Fatalf("reading vectors: %v", err)
	}

	var v merkleVectors
	if err := json.Unmarshal(raw, &v); err != nil {
		t.Fatalf("parsing vectors: %v", err)
	}
	if len(v.Leaves) == 0 || len(v.Roots) == 0 {
		t.Fatal("vectors file is empty; regenerate with forge test --match-test test_emitVectors -vv")
	}
	return v
}

func mustBigInt(t *testing.T, s string) *big.Int {
	t.Helper()
	n, ok := new(big.Int).SetString(s, 10)
	if !ok {
		t.Fatalf("not a decimal integer: %q", s)
	}
	return n
}

// syntheticTable rebuilds the table GenerateVectors.t.sol uses: recipient i is address(0x1000+i)
// and amount is (i+1) * 1e18.
func syntheticTable(roundID *big.Int, n int) []common.Hash {
	leaves := make([]common.Hash, n)
	oneEther := new(big.Int).Exp(big.NewInt(10), big.NewInt(18), nil)

	for i := 0; i < n; i++ {
		recipient := common.BigToAddress(big.NewInt(int64(0x1000 + i)))
		amount := new(big.Int).Mul(big.NewInt(int64(i+1)), oneEther)
		leaves[i] = LeafHash(roundID, uint64(i), recipient, amount)
	}
	return leaves
}

func TestLeafHashMatchesSolidity(t *testing.T) {
	for _, v := range loadVectors(t).Leaves {
		got := LeafHash(
			mustBigInt(t, v.RoundID),
			v.Index,
			common.HexToAddress(v.Recipient),
			mustBigInt(t, v.Amount),
		)
		if got.Hex() != v.Leaf {
			t.Errorf("leaf mismatch for round %s index %d\n  go:       %s\n  solidity: %s",
				v.RoundID, v.Index, got.Hex(), v.Leaf)
		}
	}
}

func TestRootMatchesSolidity(t *testing.T) {
	for _, v := range loadVectors(t).Roots {
		tree := BuildMerkleTree(syntheticTable(mustBigInt(t, v.RoundID), v.Size))
		if tree == nil {
			t.Fatalf("size %d: BuildMerkleTree returned nil", v.Size)
		}
		if tree.Root().Hex() != v.Root {
			t.Errorf("root mismatch at size %d\n  go:       %s\n  solidity: %s",
				v.Size, tree.Root().Hex(), v.Root)
		}
	}
}

// TestProofsVerifyForEverySize walks every leaf of every tree shape from 1 to 33. Odd levels
// promote their trailing node, and the depth at which that happens changes with the size, so a
// bug in the promotion rule only shows up at particular sizes.
func TestProofsVerifyForEverySize(t *testing.T) {
	roundID := big.NewInt(1)

	for n := 1; n <= 33; n++ {
		leaves := syntheticTable(roundID, n)
		tree := BuildMerkleTree(leaves)
		if tree == nil {
			t.Fatalf("size %d: nil tree", n)
		}

		for i := 0; i < n; i++ {
			if !VerifyProof(tree.Root(), leaves[i], tree.Proof(i)) {
				t.Errorf("size %d: proof failed for leaf %d", n, i)
			}
		}
	}
}

func TestProofRejectsForeignLeaf(t *testing.T) {
	roundID := big.NewInt(1)
	leaves := syntheticTable(roundID, 8)
	tree := BuildMerkleTree(leaves)

	// A leaf that is not in the tree must not verify against any member's proof.
	foreign := LeafHash(roundID, 99, common.BigToAddress(big.NewInt(0xDEAD)), big.NewInt(1))
	if VerifyProof(tree.Root(), foreign, tree.Proof(0)) {
		t.Error("a leaf outside the tree verified")
	}
}

func TestBuildMerkleTreeRejectsEmptyInput(t *testing.T) {
	// An empty tree has no meaningful root. Returning the zero hash would let an empty allocation
	// masquerade as a real one, so nil is the only safe answer.
	if BuildMerkleTree(nil) != nil {
		t.Error("expected nil for empty leaves")
	}
	if BuildMerkleTree([]common.Hash{}) != nil {
		t.Error("expected nil for zero-length leaves")
	}
}

// TestTreeDoesNotAliasCallerSlice guards a subtle failure: if the tree kept the caller's slice, a
// later mutation would silently change a root that had already been signed.
func TestTreeDoesNotAliasCallerSlice(t *testing.T) {
	leaves := syntheticTable(big.NewInt(1), 4)
	tree := BuildMerkleTree(leaves)
	before := tree.Root()

	leaves[0] = common.HexToHash("0xdeadbeef")

	if tree.Root() != before {
		t.Error("mutating the caller's slice changed the tree root")
	}
}

func TestHashPairIsCommutative(t *testing.T) {
	a := common.HexToHash("0x01")
	b := common.HexToHash("0xff")

	// Sorted-pair hashing is what lets proofs omit direction bits; the Solidity verifier relies
	// on it being genuinely order-independent.
	if hashPair(a, b) != hashPair(b, a) {
		t.Error("hashPair is not commutative")
	}
}

func TestBytesLessMatchesBigEndianOrder(t *testing.T) {
	cases := []struct {
		a, b string
		want bool
	}{
		{"0x00", "0x01", true},
		{"0x01", "0x00", false},
		{"0x01", "0x01", false},
		{
			"0x0000000000000000000000000000000000000000000000000000000000000001",
			"0x1000000000000000000000000000000000000000000000000000000000000000",
			true,
		},
		{
			// Differs only in the final byte: catches an implementation that stops comparing early.
			"0x00000000000000000000000000000000000000000000000000000000000000fe",
			"0x00000000000000000000000000000000000000000000000000000000000000ff",
			true,
		},
	}

	for _, c := range cases {
		got := bytesLess(common.HexToHash(c.a), common.HexToHash(c.b))
		if got != c.want {
			t.Errorf("bytesLess(%s, %s) = %v, want %v", c.a, c.b, got, c.want)
		}
	}
}
